### ISSUE TITLE
Regex for file doesn't work

### ISSUE THREAD

**Issue by natcl** [w4tsn/node-red-contrib-protobuf#6]
I'm not sure what this regex is supposed to check: validate:RED.validators.regex(/^(\/[^\/ ]*)+\/?$/)
but it pretty much seems to fail for any path I try to put into the field...

**Comment by w4tsn** [comment]
Good point. The idea was - if I recall it correctly - to at least not allow spaces or double slashes in the file path. I think I will remove the validator all together - more harm than good right now.
